# Week 3 Assignment
* Download the "Week_3_Assignment.ipynb" notebook 
* Fill in the code in the cells marked with `# YOUR ANSWER HERE:` by answering the question/task defined in the cell above it starting with `GRADED:`
* Code cells outside of `# YOUR ANSWER HERE:` will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it!

In [1]:
# PLEASE, DO NOT MODIFY THIS CELL!

# IMPORT NECESSARY LIBRARIES AND DATA
import pandas as pd
import numpy as np

# SECtION A data
nparr = np.arange(145, 217).reshape(12, 6)

# data location
data_url = 'https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv'
a_df = pd.read_csv(data_url, header=0)
a_df.head()


iata                            airport               city state country  \
0  ORD       Chicago O'Hare International            Chicago    IL     USA   
1  ATL  William B Hartsfield-Atlanta Intl            Atlanta    GA     USA   
2  DFW    Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   
3  PHX   Phoenix Sky Harbor International            Phoenix    AZ     USA   
4  DEN                        Denver Intl             Denver    CO     USA   

         lat        long    cnt  
0  41.979595  -87.904464  25129  
1  33.640444  -84.426944  21925  
2  32.895951  -97.037200  20662  
3  33.434167 -112.008056  17290  
4  39.858408 -104.667002  13781

In [2]:
nparr

array([[145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156],
       [157, 158, 159, 160, 161, 162],
       [163, 164, 165, 166, 167, 168],
       [169, 170, 171, 172, 173, 174],
       [175, 176, 177, 178, 179, 180],
       [181, 182, 183, 184, 185, 186],
       [187, 188, 189, 190, 191, 192],
       [193, 194, 195, 196, 197, 198],
       [199, 200, 201, 202, 203, 204],
       [205, 206, 207, 208, 209, 210],
       [211, 212, 213, 214, 215, 216]])

## GRADED SECTION A

1. Determine the shape, number of dimensions and type of elements in the numpy array `nparr`
2. Determine the standard deviation of all elements in `nparr`
3. Determine the position (not the value) of the maximum value element in `nparr`
4. Create an array of the same shape as `nparr` but filled with zeros
5. Create an array of the same shape as `nparr` but filled with ones
6. Create an array of the same shape as `nparr` but where all elements are the square root values
7. Create an array result of shape `12` by `12` resulting from multiplication of nparr with transpose(`nparr`). Hint: use `np.dot`

In [3]:
# YOUR SECTION A ANSWER HERE (please use comments to number each of your answers)

#1

print(nparr.shape)
print(nparr.ndim)
print(nparr.dtype)

#2

print(nparr.std())

#3

print(np.argmax(nparr))

#4

print(np.zeros((12,6)))

#5 

print(np.ones((12,6)))

#6 

print(np.sqrt(nparr))

#7 

nparr.dot(nparr.T)

(12, 6)
2
int32
20.7826049057058
71
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[12.04159458 12.08304597 12.12435565 12.16552506 12.20655562 12.24744871]
 [12.28820573 12.32882801 12.36931688 12.40967365 12.4498996  12.489996  ]
 [12.52996409 12.56980509 12.60952021 12.64911064 12.68857754 12.72792206]
 [12.76714533 12.80624847 12.84523258 12.88409873 12.92284798 12.9614814 ]
 [13.         13.03840481 13.07669683 13.11487705 13.15294644 13.19090596]
 [13.22875656 13.26649916 13.3041347  13.34166406 13.37908816 13.41640786]
 [13.453

array([[130555, 135865, 141175, 146485, 151795, 157105, 162415, 167725,
        173035, 178345, 183655, 188965],
       [135865, 141391, 146917, 152443, 157969, 163495, 169021, 174547,
        180073, 185599, 191125, 196651],
       [141175, 146917, 152659, 158401, 164143, 169885, 175627, 181369,
        187111, 192853, 198595, 204337],
       [146485, 152443, 158401, 164359, 170317, 176275, 182233, 188191,
        194149, 200107, 206065, 212023],
       [151795, 157969, 164143, 170317, 176491, 182665, 188839, 195013,
        201187, 207361, 213535, 219709],
       [157105, 163495, 169885, 176275, 182665, 189055, 195445, 201835,
        208225, 214615, 221005, 227395],
       [162415, 169021, 175627, 182233, 188839, 195445, 202051, 208657,
        215263, 221869, 228475, 235081],
       [167725, 174547, 181369, 188191, 195013, 201835, 208657, 215479,
        222301, 229123, 235945, 242767],
       [173035, 180073, 187111, 194149, 201187, 208225, 215263, 222301,
        229339, 236377, 

## GRADED SECTION B

The dataframe `a_df` loads the dataset that contains information on a number of categories regarding traffic (variable `cnt` represents the actual traffic) at US airports from February 2011.
The dataset has already been loaded for you in the first code cell above.
 1. Print the number of rows for the subset of the dataframe for which traffic values are higher than `10,000` (ideally, you should format the print to put the thousands comma separator--as in `23,400` instead of `23400`
 2. Print the names of all the columns of the dataframe
 3. Print a subset of the dataframe containing the `10th` and the `3rd` rows of the original dataframe (`in that order`).
 4. Which US `state` has the `8th` largest __total__ airport traffic? Please, make sure you use the correct variable as described above.
 5. Which state has the second-most __total__ number of airports (i.e. the second-most amount of airports)?
 6. Of the cities that have multiple airports, which one has the least total traffic for all airports?
 7. What is the total airport traffic for all states that border the state of Massachusetts?


In [8]:
# YOUR SECTION B ANSWER HERE (please use comments to number each of your answers)

#1


above_10000 = a_df[a_df['cnt'] > 10000]
print(len(above_10000))

#2

print(a_df.columns)

#3 


tworows = a_df.loc[[9,2],:]
print(tworows)

#4

print(a_df.loc[7, 'state'])

#5 

a_df.groupby(['state']).size().max()

#6 

a_df_p = a_df.pivot(index = 'city',
                        columns = 'airport',
                        values = 'cnt')
print(a_df_p)

#7

a_df.loc[(a_df['state'] == 'CT') | 
         (a_df['state'] == 'RI') | 
         (a_df['state'] == 'VT') | 
         (a_df['state'] == 'NH') | 
         (a_df['state'] == 'NY'),
         'cnt'].sum()


10
Index(['iata', 'airport', 'city', 'state', 'country', 'lat', 'long', 'cnt'], dtype='object')
  iata                          airport               city state country  \
9  CLT  Charlotte/Douglas International          Charlotte    NC     USA   
2  DFW  Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   

         lat       long    cnt  
9  35.214011 -80.943126  10490  
2  32.895951 -97.037200  20662  
CA
airport                Abilene Regional  Adams   Akron-Canton Regional  \
city                                                                     
NaN                                 NaN     NaN                    NaN   
Abilene                           382.0     NaN                    NaN   
Akron                               NaN     NaN                  445.0   
Albany                              NaN     NaN                    NaN   
Albuquerque                         NaN     NaN                    NaN   
...                                 ...     ...        

22007