**EAI 6010 Mini Project 5**
**Robotic AI Application**

In this project, I will attempt to generate a 6x12 matrix with obstacles placed in the middle of the matrix. The robot will start on the left side of the matrix and will look for the shortest path to the destination. 
This project is inspired by the wavefront planner algorithm and will use other path finding algorithms to accomplish the project. 

**1) Using Python create a script to find the shortest path from point S (start) to point G (goal) 
through a discretized workspace (6 rows by 12 columns). Use 4-connectivity.**

**2) Find a way to visualize the calculated path, including the path length, with the final state of 
the wave expansion.**

In [14]:
#Modified by Eugene Luo Author: John Hernandez

import numpy as np

#This function returns a vector refering to the possible directions the agent can move(nor obstacle nor out of bounds)
def perception(matrix,row,col):
    #first position stands for the possibility of moving up
    #Second for down, third position for left and fourth for right
    array=np.array([False,False,False,False])
    #the maximun positions of the matrix
    superiorBorder=0
    inferiorBorder=((matrix.shape)[0])-1
    leftBorder=0
    rightBorder=((matrix.shape)[1])-1
    
    #The 4 directions we can go
    up=row-1
    down=row+1
    left=col-1
    right=col+1
    #Checks if  moving up will cause an IndexOutOfBound Exception if not ,he will check if there is an obstacle
    #if no obstacle is found it'll make the  movement possible
    if(up>=superiorBorder): #Checks for IndexOutOfBound Exception
        if(matrix[up][col]==0): #Checks for obstacle
            array[0]=True

    if(down<=inferiorBorder): 
        if(matrix[down][col]==0):
            array[1]=True    

    if(left>=leftBorder):
        if(matrix[row][left]==0):
            array[2]=True

    if(right<=rightBorder):
        if(matrix[row][right]==0):
            array[3]=True
    return array

def updateMatrix(matrix,row,col):
    perceptionArray=perception(matrix,row,col)
    #The 4 directions we can go
    up=row-1
    down=row+1
    left=col-1
    right=col+1
    list=[]

    #If possible,the value of the direction we're gonna move will update with the current value of our square +1
    #moving up
    if(perceptionArray[0]):
        matrix[up][col]=matrix[row][col]+1
        list.append(up)
        list.append(col)
    #moving down
    if(perceptionArray[1]):
        matrix[down][col]=matrix[row][col]+1
        list.append(down)
        list.append(col)
    #Moving left
    if(perceptionArray[2]):
        matrix[row][left]=matrix[row][col]+1
        list.append(row)
        list.append(left)
    #Moving right:
    if(perceptionArray[3]):
        matrix[row][right]=matrix[row][col]+1
        list.append(row)
        list.append(right)

    #the list return the coordinates of the squares we can move to
    return list

def completeCoefficientsMatrix(matriz,rowGoal,colGoal):
    nuevosPunto=updateMatrix(matriz,rowGoal,colGoal)
    while(len(nuevosPunto)>0):
        row=nuevosPunto.pop(0)
        col=nuevosPunto.pop(0)
        nuevosPunto.extend(updateMatrix(matriz,row,col))

#This funcion with the matrix and its coefficients already completed, will only be in charge of getting the shortest Path
def waveFront(matrix,startingRow,StartingCol,EndingRow,EndingCol):
    print("\n -----Coefficients Matrix-------")
    completeCoefficientsMatrix(matrix,EndingRow,EndingCol)
    print(matrix)

    msj="["+str(startingRow)+"]["+str(StartingCol)+"]"
    count=matrix[startingRow][StartingCol]
    # the agent position is at first the starting row and the starting col
    currentRow=startingRow
    currentCol=StartingCol
    #variables for the border of the matrix
    superiorBorder=0
    inferiorBorder=((matrix.shape)[0])-1
    leftBorder=0
    rightBorder=((matrix.shape)[1])-1
    
    while(count!=1):
        #UP
        if(currentRow-1 >= superiorBorder):
            if(matrix[currentRow-1][currentCol]==(matrix[currentRow][currentCol]-1)): #I could've used the count -1 
                currentRow=currentRow-1
                msj=msj+"--->["+str(currentRow)+"]["+str(currentCol)+"]"
                count-=1
                continue
        #DOWN
        if(currentRow+1 <=inferiorBorder):
            if(matrix[currentRow+1][currentCol]==(matrix[currentRow][currentCol]-1)):
                 currentRow=currentRow+1
                 msj=msj+"--->["+str(currentRow)+"]["+str(currentCol)+"]"
                 count-=1
                 continue
        #LEFT
        if(currentCol-1 >=leftBorder):
            if(matrix[currentRow][currentCol-1]==(matrix[currentRow][currentCol]-1)):
                 currentCol=currentCol-1
                 msj=msj+"--->["+str(currentRow)+"]["+str(currentCol)+"]"
                 count-=1

                 continue
        #RIGHT
        if(currentCol+1 <=rightBorder):
            if(matrix[currentRow][currentCol+1]==(matrix[currentRow][currentCol]-1)):
                 currentCol=currentCol+1
                 msj=msj+"--->["+str(currentRow)+"]["+str(currentCol)+"]"
                 count-=1
                 continue
    #print(count)
    print("\n---Shortest Parth from [{},{}] to [{},{}] -----".format(startingRow,StartingCol,EndingRow,EndingCol))
    print(msj)
        


print("------Obstacles Allocation---------")
obstacle=True
default=input("do you want to use default matrix dimension(6x12) and obstacles? y/n: ")
if(default=='y'):
    obstacle=False
    nrows=6
    ncols=12
    matriz=np.zeros((nrows,ncols))
    matriz[2,3]=-1
    matriz[2,4]=-1
    matriz[2,5]=-1
    matriz[2,6]=-1
    matriz[2,7]=-1    
    matriz[2,8]=-10
    matriz[3,3]=-1
    matriz[3,4]=-1
    matriz[3,5]=-1
    matriz[3,6]=-1
    matriz[3,7]=-1
    matriz[3,8]=-1
else:
    nrows=int(input("type the number of row: "))
    ncols=int(input("type the numbers of columns: "))
    matriz=np.zeros((nrows,ncols))
while(obstacle==True):
    obstacleRow=int(input("type the row of the obstacle: "))
    obstacleCol=int(input("type the column of the obstacle: "))
    matriz[obstacleRow][obstacleCol]=-1
    option=input("do you want to add one more obstacle?? y/n: ")
    if(option!="y"):
        obstacle=False

print("\n------Start point------")
rowS=int(input("row of start point----->"))
colS=int(input("col of start point----->"))

print("\n------End point------")
rowE=int(input("row of End point----->"))
colE=int(input("col of End point----->"))
matriz[rowE][colE]=1
waveFront(matriz,rowS,colS,rowE,colE)

------Obstacles Allocation---------
do you want to use default matrix dimension(6x12) and obstacles? y/n: y

------Start point------
row of start point----->0
col of start point----->0

------End point------
row of End point----->5
col of End point----->11

 -----Coefficients Matrix-------
[[ 17.  16.  15.  14.  13.  12.  11.  10.   9.   8.   7.   6.]
 [ 16.  15.  14.  13.  12.  11.  10.   9.   8.   7.   6.   5.]
 [ 15.  14.  13.  -1.  -1.  -1.  -1.  -1. -10.   6.   5.   4.]
 [ 14.  13.  12.  -1.  -1.  -1.  -1.  -1.  -1.   5.   4.   3.]
 [ 13.  12.  11.  10.   9.   8.   7.   6.   5.   4.   3.   2.]
 [ 12.  11.  10.   9.   8.   7.   6.   5.   4.   3.   2.   1.]]

---Shortest Parth from [0,0] to [5,11] -----
[0][0]--->[1][0]--->[2][0]--->[3][0]--->[4][0]--->[5][0]--->[5][1]--->[5][2]--->[5][3]--->[5][4]--->[5][5]--->[5][6]--->[5][7]--->[5][8]--->[5][9]--->[5][10]--->[5][11]


**3) Change to 8-connectivity, recalculate, visualize and interpret the results.**

In [15]:
#Modified by Eugene Luo Created by Nicholas Swift

class Node():
    """A node class for A* Pathfinding"""

    def __init__(self, parent=None, position=None):
        self.parent = parent
        self.position = position

        self.g = 0
        self.h = 0
        self.f = 0

    def __eq__(self, other):
        return self.position == other.position


def astar(maze, start, end):
    """Returns a list of tuples as a path from the given start to the given end in the given maze"""

    # Create start and end node
    start_node = Node(None, start)
    start_node.g = start_node.h = start_node.f = 0
    end_node = Node(None, end)
    end_node.g = end_node.h = end_node.f = 0

    # Initialize both open and closed list
    open_list = []
    closed_list = []

    # Add the start node
    open_list.append(start_node)

    # Loop until you find the end
    while len(open_list) > 0:

        # Get the current node
        current_node = open_list[0]
        current_index = 0
        for index, item in enumerate(open_list):
            if item.f < current_node.f:
                current_node = item
                current_index = index

        # Pop current off open list, add to closed list
        open_list.pop(current_index)
        closed_list.append(current_node)

        # Found the goal
        if current_node == end_node:
            path = []
            current = current_node
            while current is not None:
                path.append(current.position)
                current = current.parent
            return path[::-1] # Return reversed path

        # Generate children
        children = []
        for new_position in [(0, -1), (0, 1), (-1, 0), (1, 0), (-1, -1), (-1, 1), (1, -1), (1, 1)]: # Adjacent squares

            # Get node position
            node_position = (current_node.position[0] + new_position[0], current_node.position[1] + new_position[1])

            # Make sure within range
            if node_position[0] > (len(maze) - 1) or node_position[0] < 0 or node_position[1] > (len(maze[len(maze)-1]) -1) or node_position[1] < 0:
                continue

            # Make sure walkable terrain
            if maze[node_position[0]][node_position[1]] != 0:
                continue

            # Create new node
            new_node = Node(current_node, node_position)

            # Append
            children.append(new_node)

        # Loop through children
        for child in children:

            # Child is on the closed list
            for closed_child in closed_list:
                if child == closed_child:
                    continue

            # Create the f, g, and h values
            child.g = current_node.g + 1
            child.h = ((child.position[0] - end_node.position[0]) ** 2) + ((child.position[1] - end_node.position[1]) ** 2)
            child.f = child.g + child.h

            # Child is already in the open list
            for open_node in open_list:
                if child == open_node and child.g > open_node.g:
                    continue

            # Add the child to the open list
            open_list.append(child)


def main():

    maze = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0],
            [0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

    start = (0, 0)
    end = (5, 11)

    path = astar(maze, start, end)
    print("Shortest Path Route:")
    print(path)


if __name__ == '__main__':
    main()

Shortest Path Route:
[(0, 0), (1, 1), (2, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (2, 9), (3, 10), (4, 11), (5, 11)]


By allowing the robot to move in a diagonal direction using 8-connectivity, we find that the robot can get to the goal in 12 steps rather than 16 steps under a 4-connectivity rule. Additionally, we find that the robot will choose to take a path around the top of the obstacle. 

**4)Modify the code so that the coordinates of “S” and “G” are randomly generated (obviously 
locations of those cannot be in the obstacle area). Run this simulation in a loop. At the end 
of each simulation display the path. For the sake of the exercise, repeat the loop just 3 
times. Either connectivity (4 or 8) is acceptable. For the sake of simplicity, you can restrict 
randomly generated “S”s to the left half, and “G”s to the right half.**

In [16]:
import random
startx = random.randint(0,2)
starty = random.randint(0,5)

endx = random.randint(9,11)
endy = random.randint(0,5)

print(startx)
print(starty)
print(endx)
print(endy)

0
4
9
0


In [17]:
def main():
    #create maze
    maze = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0],
            [0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
    # randomly generate a range of integers
    startx = random.randint(0,2)
    starty = random.randint(0,5)

    endx = random.randint(9,11)
    endy = random.randint(0,5)

    start = (startx, starty)
    end = (endy, endx)

    path = astar(maze, start, end)
    print("Shortest Path Using Randomly Generated Start and End Coordinates:")
    print(path)

if __name__ == '__main__':
    main()

Shortest Path Using Randomly Generated Start and End Coordinates:
[(2, 4), (1, 5), (1, 6), (1, 7), (1, 8), (2, 9), (3, 9), (4, 9), (5, 9)]


In [18]:
# using a loop to iterate three times using randomized coordinates
list = [1,2,3]
for i in list:
  if __name__ == '__main__':
      main()

Shortest Path Using Randomly Generated Start and End Coordinates:
[(1, 1), (2, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (2, 9)]
Shortest Path Using Randomly Generated Start and End Coordinates:
[(1, 0), (2, 1), (2, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (2, 9), (2, 10), (2, 11)]
Shortest Path Using Randomly Generated Start and End Coordinates:
[(2, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10)]


**5) Reflect on the results.**

In conclusion of this assignment, I used a wavefront planner algorithm to perform a 4-connectivity path finding algorithm to identify the shortest path from the start to end position. In my 8-connectivity path finding, I used an A* algorithm to find the shortest path. 

An 8-connectivity helps the robot reach its destination in fewer number of steps because they can move in a diagonal direction which allows them to skip steps that are require moving both x and y directions simultaneously. 

My final step randomly generated x,y coordinates for both the start and destination cell and iterated through a loop function three times to get three randomly generated paths while ignoring obstacles. 

**References**

Swift, N. (2020, May 29). Easy A* (star) pathfinding. Medium. Retrieved March 26, 2022, from https://medium.com/@nicholas.w.swift/easy-a-star-pathfinding-7e6689c7f7b2 

Hernandez, J. (n.d.). WaveFront/waveFront.py at master · Johnj-Hernandez/Wavefront. GitHub. Retrieved March 26, 2022, from https://github.com/johnj-hernandez/WaveFront/blob/master/waveFront.py 
